# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseData',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('land_use', models.CharField(max_length=20)),
                ('sold_as_vacant', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('square_footage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(0)])),
                ('tax_district', models.CharField(max_length=20)),
                ('neighborhood', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(0)])),
                ('land_value', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(0)])),
                ('sales_price', models.IntegerField(default=0)),
            ],
        ),
    ]
