# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_use', models.CharField(max_length=20)),
                ('sold_as_vacant', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('square_footage', models.CharField(max_length=20)),
                ('tax_district', models.CharField(max_length=20)),
                ('neighborhood', models.IntegerField(max_length=20)),
                ('land_value', models.IntegerField(default=0)),
                ('sales_price', models.IntegerField(default=0)),
            ],
        ),
    ]
