# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedata',
            name='land_use',
            field=models.CharField(max_length=30),
        ),
    ]
