# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20170424_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedata',
            name='square_footage',
            field=models.IntegerField(default=0),
        ),
    ]
