# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20170507_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedata',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='housedata',
            name='sold_as_vacant',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='housedata',
            name='tax_district',
            field=models.CharField(max_length=50),
        ),
    ]
