# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_auto_20170426_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedata',
            name='no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
